{
 "title": "resticprofile",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "status ab",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "resticprofile_backup_status{profile=\"ab\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "status local",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "resticprofile_backup_status{profile=\"local\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "bytes added (packed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "resticprofile_backup_added_bytes_packed",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "bytes added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "resticprofile_backup_added_bytes",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "backup duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "resticprofile_backup_duration_seconds",
     "legendFormat": "{{profile}}"
    }
   ]
  }
 ]
}